// <copyright file="Program.cs" company="PublicDomain.com">
//     CC0 1.0 Universal (CC0 1.0) - Public Domain Dedication
//     https://creativecommons.org/publicdomain/zero/1.0/legalcode
// </copyright>
// <auto-generated />

using System;
using System.Windows.Forms;

namespace FlattenFolderMenu
{
    /// <summary>
    /// Class with program entry point.
    /// </summary>
    internal sealed class Program
    {
        /// <summary>
        /// Program entry point.
        /// </summary>
        [STAThread]
        private static void Main(string[] args)
        {
            Application.EnableVisualStyles();
            Application.SetCompatibleTextRenderingDefault(false);

            // Check for args
            if (args.Length > 0)
            {
                /* Flatten Folder */
                
                // Application.Run(new FlattenDirectoryForm(args[0]));
            }
            else
            {
                // Regular execution
                Application.Run(new MainForm());
            }
        }
    }
}
